import React, { useEffect, useRef, useState } from 'react';
import { Navigate, useNavigate, useLocation, Link, Routes, Route } from 'react-router-dom';
import { Chart } from 'chart.js/auto';
import api from './services/api';

const roles = { admin: 'Administrator', farmer: 'Farmer', collection_center: 'Collection center', processor: 'Processor', distributor: 'Distributor', retailer: 'Retailer', consumer: 'Consumer' };
const nav = [{ path: '/', label: 'Overview', icon: '◈' }, { path: '/batches', label: 'Produce batches', icon: '◌' }, { path: '/trace', label: 'Trace a product', icon: '⌁' }, { path: '/quality', label: 'Quality control', icon: '✓' }, { path: '/shipments', label: 'Shipments', icon: '→' }];

function App() { return <Routes><Route path="/login" element={<Login />} /><Route path="/trace" element={<TracePage publicPage />} /><Route path="*" element={<Protected><Shell /></Protected>} /></Routes>; }
function Protected({ children }) { return localStorage.getItem('agritrace_token') ? children : <Navigate to="/login" replace />; }
function Login() {
  const navigate = useNavigate(); const [form, setForm] = useState({ email: 'admin@agritrace.local', password: 'Admin@123' }); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setError(''); try { const { data } = await api.post('/auth/login', form); localStorage.setItem('agritrace_token', data.token); localStorage.setItem('agritrace_user', JSON.stringify(data.user)); navigate('/'); } catch (err) { setError(err.response?.data?.message || 'Could not connect to Agritrace'); } }
  return <main className="auth-page"><section className="auth-art"><div className="brand-mark">A</div><p className="eyebrow">FIELD NOTE  /  01</p><h1>From soil<br />to shelf,<br /><em>with proof.</em></h1><p className="muted">One clear record for every hand, route, and decision in your food supply chain.</p><div className="route-line"><span>FARM</span><i></i><span>TABLE</span></div></section><section className="auth-form"><div className="form-wrap"><p className="eyebrow">WELCOME BACK</p><h2>Sign in to Agritrace</h2><p className="muted">Follow today's movement across your network.</p><form onSubmit={submit}><label>Email address<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></label><label>Password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} required /></label>{error && <div className="error">{error}</div>}<button className="button primary full">Enter workspace <span>↗</span></button></form><p className="hint">Demo access: admin@agritrace.local / Admin@123</p></div></section></main>;
}
function Shell() {
  const location = useLocation(); const navigate = useNavigate(); const user = JSON.parse(localStorage.getItem('agritrace_user') || '{}'); const [sidebar, setSidebar] = useState(false);
  function logout() { localStorage.clear(); navigate('/login'); }
  return <div className="app-shell"><aside className={sidebar ? 'sidebar open' : 'sidebar'}><div className="side-brand"><span className="brand-mark small">A</span><strong>agritrace</strong><button className="close-nav" onClick={() => setSidebar(false)}>×</button></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(item => <Link key={item.path} className={location.pathname === item.path ? 'active' : ''} to={item.path} onClick={() => setSidebar(false)}><span>{item.icon}</span>{item.label}</Link>)}</nav><div className="side-footer"><div className="avatar">{(user.name || 'A')[0]}</div><div><strong>{user.name || 'Account'}</strong><small>{roles[user.role] || 'Member'}</small></div><button className="logout" onClick={logout}>↪</button></div></aside><div className="main"><header><button className="menu" onClick={() => setSidebar(true)}>☰</button><div><span className="crumb">AGRICULTURE NETWORK</span><h3>{nav.find(item => item.path === location.pathname)?.label || 'Overview'}</h3></div><div className="header-actions"><Link className="icon-button" to="/trace" title="Trace a product">⌁</Link><button className="icon-button" title="Notifications">♧</button><div className="avatar header-avatar">{(user.name || 'A')[0]}</div></div></header><div className="content"><Routes><Route path="/" element={<Dashboard user={user} />} /><Route path="/batches" element={<Batches user={user} />} /><Route path="/trace" element={<TracePage />} /><Route path="/quality" element={<Quality />} /><Route path="/shipments" element={<Shipments />} /></Routes></div></div></div>;
}
function Dashboard({ user }) {
  const [data, setData] = useState(null); useEffect(() => { api.get('/dashboard').then(r => setData(r.data)).catch(() => setData({})); }, []);
  const stats = [['Total batches', data?.total_batches ?? '—', 'registered produce'], ['Network quantity', data?.total_quantity ? `${Number(data.total_quantity).toLocaleString()} kg` : '—', 'across all batches'], ['In transit', data?.in_transit ?? '—', 'moving right now'], ['Approved', data?.approved ?? '—', 'quality cleared']];
  return <><div className="welcome"><div><p className="eyebrow">{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).toUpperCase()}</p><h1>Good morning, {user.name?.split(' ')[0] || 'there'}.</h1><p className="muted">Here is the pulse of your supply chain today.</p></div><Link className="button primary" to="/batches">+ Register produce</Link></div><div className="stat-grid">{stats.map(([title, value, note]) => <div className="stat" key={title}><span>{title}</span><strong>{value}</strong><small>{note}</small></div>)}</div><div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">VOLUME BY CATEGORY</p><h2>What is moving</h2></div><span className="live-dot">LIVE</span></div><BarChart data={data?.categories || []} /></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Network pulse</h2></div><Link to="/batches" className="text-link">View all →</Link></div><div className="activity-list">{(data?.activity || []).map((item, i) => <div className="activity" key={item.id || i}><span className="activity-icon">{i % 2 ? '↗' : '✓'}</span><div><strong>{item.action}</strong><p>{item.produce_name} · {item.actor_name || 'System'}</p></div><time>{item.created_at?.slice(0, 10)}</time></div>)}{!data?.activity?.length && <p className="empty">No activity yet. Register your first batch to begin.</p>}</div></section></div><div className="callout"><div><span className="callout-icon">⌁</span><div><p className="eyebrow">PUBLIC TRACEABILITY</p><h2>Give every product a story people can trust.</h2></div></div><Link className="button light" to="/trace">Open product search ↗</Link></div></>;
}
function BarChart({ data }) { const ref = useRef(null); useEffect(() => { if (!ref.current) return; const chart = new Chart(ref.current, { type: 'bar', data: { labels: data.map(x => x.category), datasets: [{ data: data.map(x => x.quantity), backgroundColor: ['#d65a3b','#e8a24c','#6d9d70','#305c4d'], borderRadius: 3, barThickness: 28 }] }, options: { responsive: true, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#65706b' } }, y: { grid: { color: '#e6e8df' }, ticks: { color: '#65706b' } } } } }); return () => chart.destroy(); }, [data]); return <div className="chart-wrap"><canvas ref={ref}></canvas></div>; }
function Batches({ user }) { const [batches, setBatches] = useState([]); const [formOpen, setFormOpen] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ produce_name: '', category: 'Vegetables', variety: '', quantity: '', unit: 'kg', farm_location: '' }); const canAdd = ['admin', 'farmer'].includes(user.role); const load = () => api.get('/batches').then(r => setBatches(r.data)); useEffect(load, []); async function add(e) { e.preventDefault(); try { await api.post('/batches', form); setFormOpen(false); setForm({ ...form, produce_name: '', quantity: '' }); load(); } catch (err) { setError(err.response?.data?.message || 'Could not save batch'); } } return <><div className="page-heading"><div><p className="eyebrow">PRODUCE REGISTER</p><h1>Every batch, accounted for.</h1><p className="muted">Create and follow the identity of produce from harvest onward.</p></div>{canAdd && <button className="button primary" onClick={() => setFormOpen(!formOpen)}>+ Register produce</button>}</div>{formOpen && <form className="panel inline-form" onSubmit={add}><label>Produce name<input required value={form.produce_name} onChange={e => setForm({ ...form, produce_name: e.target.value })} placeholder="e.g. Roma tomatoes" /></label><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option>Vegetables</option><option>Fruits</option><option>Grains</option><option>Herbs</option></select></label><label>Quantity<input required type="number" min="1" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} placeholder="0" /></label><label>Farm location<input value={form.farm_location} onChange={e => setForm({ ...form, farm_location: e.target.value })} placeholder="Region or farm" /></label><button className="button primary">Save batch</button>{error && <div className="error">{error}</div>}</form>}<section className="panel table-panel"><div className="table-toolbar"><div><p className="eyebrow">LIVE REGISTER</p><h2>{batches.length} tracked batches</h2></div><input className="search" placeholder="Search batches..." onChange={e => api.get(`/batches?search=${e.target.value}`).then(r => setBatches(r.data))} /></div><div className="table-scroll"><table><thead><tr><th>Trace ID</th><th>Produce</th><th>Farmer</th><th>Quantity</th><th>Current location</th><th>Status</th></tr></thead><tbody>{batches.map(b => <tr key={b.id}><td><Link className="trace-id" to={`/trace?batch=${b.trace_id}`}>{b.trace_id}</Link></td><td><strong>{b.produce_name}</strong><small>{b.category}{b.variety ? ` · ${b.variety}` : ''}</small></td><td>{b.farmer_name}</td><td>{Number(b.quantity).toLocaleString()} {b.unit}</td><td>{b.current_location || '—'}</td><td><span className={`status ${b.status}`}>{b.status.replace('_', ' ')}</span></td></tr>)}</tbody></table>{!batches.length && <p className="empty">No batches match this search.</p>}</div></section></>; }
function TracePage({ publicPage = false }) { const [id, setId] = useState(new URLSearchParams(useLocation().search).get('batch') || ''); const [result, setResult] = useState(null); const [error, setError] = useState(''); async function search(e) { e?.preventDefault(); setError(''); try { setResult((await api.get(`/traceability/${id.trim()}`)).data); } catch (err) { setResult(null); setError(err.response?.data?.message || 'Product not found'); } } return <div className={publicPage ? 'trace-public' : ''}>{publicPage && <Link className="public-brand" to="/login"><span className="brand-mark small">A</span> agritrace</Link>}<div className="page-heading trace-heading"><div><p className="eyebrow">OPEN LEDGER</p><h1>Trace a product.</h1><p className="muted">Enter a traceability ID to see the journey behind your food.</p></div></div><form className="trace-search" onSubmit={search}><input value={id} onChange={e => setId(e.target.value)} placeholder="Try AGR-2026-0001" required /><button className="button primary">Search journey ↗</button></form>{error && <div className="error">{error}</div>}{result && <section className="trace-result"><div className="trace-summary"><div><p className="eyebrow">{result.batch.trace_id}</p><h2>{result.batch.produce_name}</h2><p className="muted">{result.batch.category} · {result.batch.quantity} {result.batch.unit} · harvested {result.batch.harvest_date || 'date not recorded'}</p></div><span className={`status ${result.batch.status}`}>{result.batch.status.replace('_', ' ')}</span></div><div className="journey">{result.events.map((event, i) => <div className="journey-item" key={event.id}><div className="journey-marker">{i === result.events.length - 1 ? '●' : '✓'}</div><div><span className="eyebrow">{event.created_at?.replace('T', ' ').slice(0, 16)}</span><h3>{event.action}</h3><p>{event.location || 'Location not recorded'} · {event.actor_name || 'System'} · {event.status}</p>{event.remarks && <small>{event.remarks}</small>}</div></div>)}</div>{result.quality && <div className="quality-note"><span>✓</span><div><strong>Quality {result.quality.result}</strong><p>Grade {result.quality.grade || '—'} · {result.quality.condition_note || 'Inspection recorded'} · inspected by {result.quality.inspector_name}</p></div></div>}</section>}</div>; }
function Quality() { const [rows, setRows] = useState([]); useEffect(() => { api.get('/quality').then(r => setRows(r.data)).catch(() => {}); }, []); return <><div className="page-heading"><div><p className="eyebrow">QUALITY CONTROL</p><h1>Confidence, measured.</h1><p className="muted">Inspection records attached directly to product identity.</p></div></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Batch</th><th>Product</th><th>Inspector</th><th>Grade</th><th>Result</th><th>Inspected</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td className="trace-id">{r.trace_id}</td><td>{r.produce_name}</td><td>{r.inspector_name}</td><td>{r.grade || '—'}</td><td><span className={`status ${r.result.toLowerCase()}`}>{r.result}</span></td><td>{r.inspection_date?.slice(0, 10)}</td></tr>)}</tbody></table>{!rows.length && <p className="empty">No inspections have been recorded.</p>}</div></section></>; }
function Shipments() { const [rows, setRows] = useState([]); useEffect(() => { api.get('/shipments').then(r => setRows(r.data)).catch(() => {}); }, []); return <><div className="page-heading"><div><p className="eyebrow">MOVEMENT CONTROL</p><h1>In motion, visible.</h1><p className="muted">Keep every dispatch accountable from source to destination.</p></div></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Shipment</th><th>Batch</th><th>Route</th><th>Vehicle</th><th>Expected</th><th>Status</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td className="trace-id">{r.shipment_id}</td><td>{r.trace_id}<small>{r.produce_name}</small></td><td>{r.source || '—'} → {r.destination || '—'}</td><td>{r.vehicle_number || '—'}</td><td>{r.expected_delivery || '—'}</td><td><span className={`status ${r.status.toLowerCase().replaceAll(' ', '_')}`}>{r.status}</span></td></tr>)}</tbody></table>{!rows.length && <p className="empty">No shipments have been created.</p>}</div></section></>; }
export default App;
